"""СрChange role tabel

Revision ID: baf3d6222b84
Revises: e2e4393da5b0
Create Date: 2024-10-24 10:32:36.612192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "baf3d6222b84"
down_revision: Union[str, None] = "e2e4393da5b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column("edit_comment_time_limit", sa.Integer(), nullable=False),
    )
    op.add_column("roles", sa.Column("rate", sa.Integer(), nullable=False))
    op.add_column(
        "roles", sa.Column("refresh_time", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "refresh_time")
    op.drop_column("roles", "rate")
    op.drop_column("roles", "edit_comment_time_limit")
    # ### end Alembic commands ###
